conf/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^laakam/', include(admin.site.urls)),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^retail/', include('ikwen.partnership.urls', namespace='partnership')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^rewarding/', include('ikwen.rewarding.urls', namespace='rewarding')),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    url(r'^kakocase/', include('ikwen_kakocase.kakocase.urls', namespace='kakocase')),
    url(r'^kako/', include('ikwen_kakocase.kako.urls', namespace='kako')),
    url(r'^shavida/', include('ikwen_shavida.shavida.urls', namespace='shavida')),
    url(r'^webnode/', include('ikwen_webnode.webnode.urls', namespace='webnode')),
    url(r'^daraja/', include('daraja.urls', namespace='daraja')),
    url(r'^foulassi/', include('ikwen_foulassi.foulassi.urls', namespace='foulassi')),
    url(r'^ywehot/', include('ywehot.urls', namespace='ywehot')),
    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),
    url(r'^tsunami/', include('tsunami.urls', namespace='tsunami')),

    url(r'^echo/', include('echo.urls', namespace='echo')),
    url(r'^', include('smartevent.urls', namespace='smartevent')),
)

smartevent/urls.py
from django.conf.urls import url, patterns
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test

from smartevent.views import ViewEvent, thankyou

urlpatterns = patterns(
    '',
    url(r'^thank-you/$', thankyou, name='thankyou'),
    url(r'^(?P<slug>[-\w]+)/$', ViewEvent.as_view(), name='view_event'),
)

smartevent/models.py
from django.db import models

# Create your models here.
from django.db import models

from ikwen.core.models import Model, Country, Application


class Participant(Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    occupation = models.CharField(max_length=200)
    opinion = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return '%s %s' % (self.first_name, self.last_name)


class Event(Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.CharField(max_length=200, unique=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField(blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    country = models.ForeignKey(Country, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    facebook_link = models.URLField(blank=True, null=True)
    instagram_link = models.URLField(blank=True, null=True)
    youtube_link = models.URLField(blank=True, null=True)
    twitter_link = models.URLField(blank=True, null=True)
    linkedin_link = models.URLField(blank=True, null=True)

    def __unicode__(self):
        return self.title

smartevent/views.py
import json
from threading import Thread

from django import forms
from django.contrib import messages
from django.core.mail import EmailMessage
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.utils.translation import gettext as _, get_language, activate

# Create your views here.
from django.views.generic import TemplateView

from ikwen.core.models import Application
from ikwen.core.utils import get_model_admin_instance, get_service_instance, get_item_list, get_model, get_mail_content, \
    XEmailMessage, logger

from daraja.models import Dara
from smartevent.models import Event, Participant

ADMIN_EMAIL = 'silatchomsiaka@gmail.com'


class ParticipantForm(forms.ModelForm):
    """
    Participant form of an event
    """
    class Meta:
        model = Participant


class ViewEvent(TemplateView):
    template_name = 'smartevent/home.html'

    def get_context_data(self, **kwargs):
        context = super(ViewEvent, self).get_context_data(**kwargs)
        event = Event.objects.get(slug=kwargs['slug'])
        current_released_apps = ['daraja', 'foulassi', 'tsunami', 'pinsview']
        context['ikwen_apps'] = Application.objects.filter(slug__in=current_released_apps)
        context['event'] = event
        return context

    def post(self, request, *args, **kwargs):
        context = super(ViewEvent, self).get_context_data(**kwargs)
        event = Event.objects.get(slug=kwargs['slug'])
        form = ParticipantForm(request.POST)
        if form.is_valid():
            form.save()
            next_url = reverse('smartevent:view_event', args=(event.slug,))
            messages.success(request, "Thank you very much.")
            return HttpResponseRedirect(next_url, messages)
        else:
            context['form'] = form
            return render(request, self.template_name, context)


def thankyou(request, *args, **kwargs):
    dara_list = Dara.objects.all()
    participant_list = Participant.objects.all()
    dara_email_list = []

    sender = 'ikwen Daraja <no-reply@ikwen.com>'

    for dara in dara_list:
        dara_lang = dara.member.language

        if dara_lang == 'en':
            cta_url = 'https://blog.ikwen.com/from-social-network-to-daraja/'
        else:
            cta_url = 'https://blog.ikwen.com/des-reseaux-sociaux-a-daraja/'

        activate(dara_lang)
        dara_name = dara.member.first_name
        dara_email = dara.member.email
        subject = _("Start making money now !")
        html_content = get_mail_content(subject, template_name='smartevent/mails/thank-you.html',
                                        extra_context={'dara_name': dara_name,
                                                       'cta_url': cta_url})
        msg = EmailMessage(subject, html_content, sender, [dara_email])
        msg.content_subtype = "html"
        msg.extra_headers = {'Reply-To': 'contact@ikwen.com'}
        Thread(target=lambda m: m.send(), args=(msg,)).start()
        dara_email_list.append(dara_email)

    for participant in participant_list:
        cta_url = 'https://blog.ikwen.com/des-reseaux-sociaux-a-daraja/'
        if participant.email in dara_email_list:
            continue
        lang = 'fr'
        activate(lang)
        dara_name = participant.first_name
        dara_email = participant.email
        subject = _("Start making money now !")
        html_content = get_mail_content(subject, template_name='smartevent/mails/thank-you.html',
                                        extra_context={'dara_name': dara_name,
                                                       'cta_url': cta_url,
                                                       })
        msg = EmailMessage(subject, html_content, sender, [dara_email])
        msg.content_subtype = "html"
        msg.extra_headers = {'Reply-To': 'contact@ikwen.com'}
        Thread(target=lambda m: m.send(), args=(msg,)).start()

    response = {"success": True}
    return HttpResponse(json.dumps(response), 'content-type: text/json')

    # dara_list = [{'email': 'silatchomsiaka@gmail.com', 'name': 'Silatchom'},
    #              {'email': 'rsihon@gmail.com', 'name': 'Sihon'},
    #              {'email': 'wilfriedwillend@gmail.com', 'name': 'Wilfried'},
    #              {'email': 'cedricfotso1@gmail.com', 'name': 'Cedric'}]
    #
    # for dara in dara_list:
    #     lang = 'fr'
    #     activate(lang)
    #     dara_name = dara.get('name')
    #     dara_email = dara.get('email')
    #     subject = _("Start making money now !")
    #     html_content = get_mail_content(subject, template_name='smartevent/mails/thank-you.html',
    #                                     extra_context={'dara_name': dara_name,
    #                                                    'cta_url': cta_url,
    #                                                    })
    #     msg = EmailMessage(subject, html_content, sender, [dara_email])
    #     msg.content_subtype = "html"
    #     msg.extra_headers = {'Reply-To': 'contact@ikwen.com'}
    #     Thread(target=lambda m: m.send(), args=(msg,)).start()
    #
    # response = {"success": True}
    # return HttpResponse(json.dumps(response), 'content-type: text/json')

smartevent/templates/smartevent/home.html
{% extends 'website/base.html' %}
{% load i18n static staticfiles humanize user_agents webdesign %}

{% block page_title %}
    <title>ikwen Daraja Conf 2019</title>
{% endblock %}

{% block header_brand %}
    <a class="navbar-brand hidden-xs" href="{{ service.url }}">
        <img src="{% static "smartevent/img/logo-ikwen_for-header_white.png" %}" alt="ikwen-logo" style="height: 30px; ">
    </a>
    <strong class="navbar-brand visible-xs">{{ service.project_name }}</strong>
{% endblock %}

{% block head_style %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'smartevent/css/daraja_conference_2019.css' %}?v=19.12.03">

{% endblock %}

{% block content %}
    <div>
        <div class="banner-top">
            <div class="banner-container">
                <div class="container">
                    <div class="col-md-8 parent-header">
                        <div class="header">
                            {% blocktrans %}
                                <h1 class="welcome-message">Welcome to ikwen Daraja conf 2019 !</h1>
                                <p style="font-weight: lighter; text-align: justify">
                                    <h3>Thanks for attending this conference</h3>
                                </p>
                            {% endblocktrans %}
{#                                    In case you missed any of the sessions or want to go back and rewatch your favorites, we’ve got you covered. Recordings of all talks are posted on YouTube. Keep the conversation going using #ikwenConf2019.#}
{#                                <div class="form-row col-sm-6 col-xs-12 watch-previous-session">#}
{#                                    <button type="button" class="btn btn-primary btn-block">WATCH SESSION RECORDINGS</button>#}
{#                                </div>#}

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="second-section">
             <div id="content" class="container">
        {#    <div id="content" class="container" style="background-image: url({% static 'enfinchezmoi/img/video_home_page.gif' %}); background-size: cover; background-repeat: no-repeat; background-position: center;height: 500px; width: inherit;">#}
                <div class="col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                    <h2 class="confirm-participation">{% trans "Confirm your participation" %}</h2>
                    <form method="post">{% csrf_token %}
                        {% if form.errors %}
                            <div class="errorlist">{{ form.errors }}</div>
                        {% endif %}
                        <div class="form-group">
                            <label for="first-name">{% trans "First name:" %}</label>
                            <input id="first-name" name="first_name" type="text" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="last-name">{% trans "Last name:" %}</label>
                            <input id="last-name" name="last_name" type="text" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="email">{% trans "Email:" %}</label>
                            <input id="email" name="email" type="email" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="phone">{% trans "Phone:" %}</label>
                            <input id="phone" name="phone" type="text" class="form-control">
                        </div>
                        <div class="form-group occupation">
                            <label for="occupation">{% trans "Occupation:" %}</label>
                            <select id="occupation" name="occupation" class="form-control">
                                <option selected>{% trans "Entrepreneur" %}</option>
                                <option>{% trans "Digital marketist" %}</option>
                                <option>{% trans "Media professional" %}</option>
                                <option>{% trans "Influencer" %}</option>
                                <option>{% trans "Seeking to become digital marketist" %}</option>
                                <option>{% trans "Other" %}</option>
                            </select>
                            <div class="clearfix"></div>
                        </div>
                        <div class="form-group other-occupation" style="display: none">
                            <input type="text" placeholder="Specify your occupation" class="form-control">
                            <div class="clearfix"></div>
                        </div>
                       <div class="form-group">
                           <label for="live-word">{% trans "Leave some words:" %}</label>
                           <textarea class="form-control" name="opinion"></textarea>
                       </div>
                        <div class="form-row col-md-6 col-sm-6 submit-container" style="float: none; margin: 5vh auto;">
                            <button class="btn btn-primary btn-block submit">{% trans "Submit" %}</button>
                        </div>
                    </form>
                    <div class="form-row col-md-6 col-sm-6 submit-container" style="float: none; margin: 5vh auto;">
                        <button class="btn btn-block btn-info send-bulk-email" role="button">Send emails to participants</button>
                    </div>
                </div>



                {#    Modal declaration : BEGIN #}
{#                <div class="modal fade" id="thanks" tabindex="-1" role="dialog">#}
{#                    <div class="modal-dialog" role="document">#}
{#                        <div class="modal-content modal-info" style="background-image: url({% static 'daraja/img/architecture-entreprise.jpg' %});">#}
{#                            <div class="modal-body text-center">#}
{#                                <h4 id="thanks-msg" style="color: #fff;">{% blocktrans %}ikwen thanks you for your kind attention.{% endblocktrans %}</h4>#}
{#                            </div>#}
{#                            <div>#}
{#                                <div class="actions">#}
{#                                    <div class="col-xs-12 col-sm-4 col-md-3 pull-right action">#}
{#                                        <button class="btn btn-default btn-block btn-sm" data-dismiss="modal" aria-label="OK">{% trans "OK" %}</button>#}
{#                                    </div>#}
{#                                </div>#}
{#                                <div class="clearfix"></div>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
                {#    Modal declaration : END #}
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    <footer class="footer">
        <div class="container">
            <div class="row" style="margin-bottom: 15px">
                <div class="col-sm-3" style="margin-top: 4vh; text-align: center;">
                    <a href="{% url 'daraja:home' %}">
                        <img class="footer-logo" src="{% static 'smartevent/img/New logo ikwen without slogan (niveau de blanc)-.png' %}" style="max-width: 7vw;"/>
                        <h4 class="logo footer-title">ikwen</h4>
                    </a>
                </div>
                <div class="col-sm-3 col-xs-4 footer-">
                    <h5 style="color: #ffffff; font-weight: bold; font-size: 2vw; margin-top: 5vh;">{% trans 'Get started' %}</h5>
                    <ul style="font-size: 1.2vw; line-height: 1.7; list-style-type: none; padding-left: 0">
                        <li><a style="color: #d2d1d1;" href="{% url 'daraja:home' %}">{% trans 'Home' %}</a></li>
                        <li><a style="color: #d2d1d1;" href="{% url 'ikwen:sign_in' %}">{% trans 'Sign In' %}</a></li>
{#                        <li><a style="color: #d2d1d1;" href="#" target="_blank">{% trans 'Downloads' %}</a></li>#}
                    </ul>
                </div>
                <div class="col-sm-3 col-xs-4 footer-">
                    <h5 style="color: #ffffff; font-weight: bold; font-size: 2vw; margin-top: 5vh;">{% trans 'About us' %}</h5>
                    <ul style=" font-size: 1.2vw; line-height: 1.7; list-style-type: none; padding-left: 0">
                        <li><a style="color: #d2d1d1;" href="{% url 'about' %}" target="_blank">{% trans 'Our Company' %}</a></li>
                        {% include 'website/snippets/language_switcher.html' %}
{#                        <li><a style="color: #d2d1d1;" href="#" target="_blank">{% trans 'Contact us' %}</a></li>#}
{#                        <li><a style="color: #d2d1d1;" href="{% url 'daraja:for_businesses' %}" target="_blank">{% trans 'For business' %}</a></li>#}
                    </ul>
                </div>
                <div class="col-sm-3 col-xs-4 footer-">
                    <h5 style="color: #ffffff; font-weight: bold; font-size: 2vw; margin-top: 5vh;">Support</h5>
                    <ul style="font-size: 1.2vw; line-height: 1.7; list-style-type: none; padding-left: 0">
                        <li><a style="color: #d2d1d1;" href="http://blog.ikwen.com/" target="_blank">Blog</a></li>
                        <li><a style="color: #d2d1d1;" href="http://support.ikwen.com/" target="_blank">{% trans 'Help desk' %}</a></li>
{#                        <li><a style="color: #d2d1d1; text-decoration: none" href="#" target="_blank">Forums</a></li>#}
                    </ul>
                </div>
{#                <div class="col-sm-3 footer-">#}
{#                    <div class="social-networks" style="padding-bottom: 16px; padding-top: 30px; text-align: center">#}
{#                        <a style="color: #f9f9f9; padding: 10px; text-decoration: none; transition: 0.2s;" href="#" class="twitter"><i class="fa fa-twitter"></i></a>#}
{#                        <a style="color: #f9f9f9; padding: 10px; text-decoration: none; transition: 0.2s;" href="#" class="facebook"><i class="fa fa-facebook"></i></a>#}
{#                        <a style="color: #f9f9f9; padding: 10px; text-decoration: none; transition: 0.2s;" href="#" class="google"><i class="fa fa-google-plus"></i></a>#}
{#                    </div>#}
{#                    <button type="button" class="btn btn-default">Contact us</button>#}
{#                </div>#}
            </div>
        </div>

        <div class="footer-copyright " style="padding: 3px 0; text-align: center;">
            &copy; {{ year }} <a class="company-name" href="{{ service.url }}"><strong style="color: #ffffff">{{ config.company_name }}</strong></a>.
        </div>
    </footer>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script>
        (() => {
            $('#occupation').change(function () {
                if ($(this).val() === 'Other') {
                    $('.form-group.other-occupation').show();
                    $('.form-group.other-occupation input').attr('name', 'occupation');
                    $('.form-group.occupation select').removeAttr('name');
                } else {
                    $('.form-group.other-occupation').hide();
                    $('.form-group.other-occupation input').removeAttr('name', 'occupation');
                    $('.form-group.occupation select').attr('name', 'occupation');
                }
            });
            {% if messages %}
                {% for msg in messages %}ikwen.showFloatingNotice('{{ msg|safe }}', '{{ msg.tags }}', 6);{% endfor %}
            {% endif %}

            $('.send-bulk-email').click(function () {
                $.getJSON("{% url 'smartevent:thankyou' %}", {}, function (data, status, xhr) {
                    if(data.success){
                        console.log("Emails have completely sent")
                    } else {
                      console.log("Emails failed to go")
                    }
                });
            });

        })()
    </script>
{% endblock %}